import { Box, Boxes, Pencil, Plus, Settings2, Trash2, Wrench } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { MoneyInput } from '../../components/forms/MoneyInput'
import { NumberInput } from '../../components/forms/NumberInput'
import { Button } from '../../components/ui/Button'
import { Card } from '../../components/ui/Card'
import { ConfirmDialog } from '../../components/ui/ConfirmDialog'
import { DataError, DataLoading } from '../../components/ui/DataState'
import { EmptyState } from '../../components/ui/EmptyState'
import { Input } from '../../components/ui/Input'
import { Modal } from '../../components/ui/Modal'
import { Select } from '../../components/ui/Select'
import { Table } from '../../components/ui/Table'
import { useToast } from '../../components/ui/Toast'
import { useFilaments, type FilamentInput } from '../../hooks/useFilaments'
import { useMachines, type MachineInput } from '../../hooks/useMachines'
import { useSettings, type SettingsInput } from '../../hooks/useSettings'
import { useSupplies, type SupplyInput, type SupplyUnit } from '../../hooks/useSupplies'
import { getDatabaseErrorMessage } from '../../lib/databaseErrors'
import { formatCurrency, parseNumberBR } from '../../lib/formatters'
import type { FilamentRow, MachineRow, SupplyRow } from '../../types/database'

type Tab = 'filaments' | 'machines' | 'supplies' | 'settings'
const tabs: Array<{ id: Tab; label: string; icon: typeof Boxes }> = [
  { id: 'filaments', label: 'Filamentos', icon: Boxes },
  { id: 'machines', label: 'Máquinas', icon: Wrench },
  { id: 'supplies', label: 'Insumos e embalagens', icon: Box },
  { id: 'settings', label: 'Parâmetros globais', icon: Settings2 },
]

export function Costs() {
  const [active, setActive] = useState<Tab>('filaments')
  return <div className="space-y-6"><div className="flex gap-2 overflow-x-auto rounded-2xl border border-border bg-white p-2 shadow-card">{tabs.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => setActive(id)} className={`flex min-h-11 shrink-0 items-center gap-2 rounded-xl px-4 text-sm font-semibold transition ${active === id ? 'bg-primary text-white' : 'text-slate-600 hover:bg-slate-50'}`}><Icon size={18} />{label}</button>)}</div>{active === 'filaments' && <FilamentsPanel />}{active === 'machines' && <MachinesPanel />}{active === 'supplies' && <SuppliesPanel />}{active === 'settings' && <SettingsPanel />}</div>
}

function FilamentsPanel() {
  const hook = useFilaments(); const { showToast } = useToast()
  const [open, setOpen] = useState(false); const [editing, setEditing] = useState<FilamentRow | null>(null); const [deleting, setDeleting] = useState<FilamentRow | null>(null); const [saving, setSaving] = useState(false)
  const close = () => { setOpen(false); setEditing(null) }
  const submit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const data = new FormData(event.currentTarget)
    const input: FilamentInput = { type_brand: String(data.get('type_brand')).trim(), color: String(data.get('color')).trim(), weight_kg: parseNumberBR(String(data.get('weight_kg'))), price_paid: parseNumberBR(String(data.get('price_paid'))), supplier_image_url: nullable(data.get('supplier_image_url')) }
    if (!input.type_brand || !input.color || input.weight_kg <= 0 || input.price_paid < 0) { showToast('Preencha corretamente os campos obrigatórios.', 'error'); return }
    setSaving(true); try { if (editing) await hook.updateFilament(editing.id, input); else await hook.createFilament(input); showToast(editing ? 'Filamento atualizado com sucesso.' : 'Filamento adicionado ao estoque.', 'success'); close() } catch (error) { showToast(getDatabaseErrorMessage(error, 'Erro ao salvar filamento.'), 'error') } finally { setSaving(false) }
  }
  const remove = async () => { if (!deleting) return; try { await hook.deleteFilament(deleting.id); showToast('Filamento excluído com sucesso.', 'success'); setDeleting(null) } catch (error) { showToast(getDatabaseErrorMessage(error, 'Erro ao excluir filamento.'), 'error') } }
  return <Card title="Inventário de filamentos" description="Controle peso, custo e disponibilidade real." action={<Button onClick={() => setOpen(true)}><Plus size={18} />Adicionar ao estoque</Button>}>
    {hook.loading ? <DataLoading /> : hook.error ? <DataError message={getDatabaseErrorMessage(new Error(hook.error), 'Erro ao carregar filamentos.')} /> : hook.filaments.length === 0 ? <EmptyState icon={Boxes} title="Nenhum filamento cadastrado" description="Cadastre o primeiro rolo para começar a controlar seus custos." action={<Button onClick={() => setOpen(true)}><Plus size={18} />Adicionar filamento</Button>} /> : <Table headers={['Filamento', 'Cor', 'Estoque real', 'Reservado', 'Livre', 'Preço pago', 'Preço/grama', 'Ações']}>{hook.filaments.map((item) => <tr key={item.id}><Cell strong>{item.type_brand}</Cell><Cell>{item.color}</Cell><Cell>{item.stock_real_g.toLocaleString('pt-BR')} g</Cell><Cell>{item.stock_reserved_g.toLocaleString('pt-BR')} g</Cell><Cell success>{(item.stock_real_g - item.stock_reserved_g).toLocaleString('pt-BR')} g</Cell><Cell>{formatCurrency(item.price_paid)}</Cell><Cell>{formatCurrency(item.price_per_gram)}</Cell><Actions onEdit={() => { setEditing(item); setOpen(true) }} onDelete={() => setDeleting(item)} /></tr>)}</Table>}
    <Modal open={open} onClose={close} title={editing ? 'Editar filamento' : 'Adicionar filamento'} footer={<><Button variant="outline" onClick={close}>Cancelar</Button><Button type="submit" form="filament-form" loading={saving}>{editing ? 'Salvar alterações' : 'Adicionar ao estoque'}</Button></>}><form id="filament-form" key={editing?.id ?? 'new'} className="grid gap-4 sm:grid-cols-2" onSubmit={submit}><Input name="type_brand" label="Tipo / marca *" defaultValue={editing?.type_brand} required /><Input name="color" label="Cor *" defaultValue={editing?.color} required /><NumberInput name="weight_kg" label="Peso em kg *" defaultValue={editing?.weight_kg} min="0.001" step="0.001" required /><MoneyInput name="price_paid" label="Preço pago *" defaultValue={editing?.price_paid} required /><Input containerClassName="sm:col-span-2" name="supplier_image_url" type="url" label="URL da foto do fornecedor" defaultValue={editing?.supplier_image_url ?? ''} /></form></Modal>
    <ConfirmDialog open={Boolean(deleting)} title="Excluir filamento?" description="Esta ação excluirá o filamento e seu histórico. Filamentos vinculados a orçamentos não podem ser excluídos." confirmLabel="Excluir" onCancel={() => setDeleting(null)} onConfirm={() => void remove()} />
  </Card>
}

function MachinesPanel() {
  const hook = useMachines(); const { showToast } = useToast(); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<MachineRow | null>(null); const [deleting, setDeleting] = useState<MachineRow | null>(null); const [saving, setSaving] = useState(false)
  const close = () => { setOpen(false); setEditing(null) }
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const input: MachineInput = { model: String(data.get('model')).trim(), consumption_watts: parseNumberBR(String(data.get('consumption_watts'))), maintenance_per_hour: parseNumberBR(String(data.get('maintenance_per_hour'))), machine_value: parseNumberBR(String(data.get('machine_value'))), estimated_life_hours: parseNumberBR(String(data.get('estimated_life_hours'))) }; if (!input.model || input.consumption_watts < 0 || input.maintenance_per_hour < 0 || input.machine_value < 0 || input.estimated_life_hours <= 0) { showToast('Preencha corretamente os campos obrigatórios.', 'error'); return } setSaving(true); try { await hook.saveMachine(input, editing?.id); showToast(editing ? 'Máquina atualizada com sucesso.' : 'Máquina cadastrada com sucesso.', 'success'); close() } catch (error) { showToast(getDatabaseErrorMessage(error, 'Erro ao salvar máquina.'), 'error') } finally { setSaving(false) } }
  const remove = async () => { if (!deleting) return; try { await hook.deleteMachine(deleting.id); showToast('Máquina excluída com sucesso.', 'success'); setDeleting(null) } catch (error) { showToast(getDatabaseErrorMessage(error, 'Erro ao excluir máquina.'), 'error') } }
  return <Card title="Máquinas" description="Cadastre os custos operacionais das suas impressoras." action={<Button onClick={() => setOpen(true)}><Plus size={18} />Adicionar máquina</Button>}>{hook.loading ? <DataLoading /> : hook.error ? <DataError message={getDatabaseErrorMessage(new Error(hook.error), 'Erro ao carregar máquinas.')} /> : hook.machines.length === 0 ? <EmptyState icon={Wrench} title="Nenhuma máquina cadastrada" description="Cadastre sua primeira impressora para calcular energia, manutenção e depreciação." action={<Button onClick={() => setOpen(true)}><Plus size={18} />Adicionar máquina</Button>} /> : <Table headers={['Modelo', 'Consumo', 'Manutenção/h', 'Valor', 'Vida útil', 'Ações']}>{hook.machines.map((item) => <tr key={item.id}><Cell strong>{item.model}</Cell><Cell>{item.consumption_watts} W</Cell><Cell>{formatCurrency(item.maintenance_per_hour)}</Cell><Cell>{formatCurrency(item.machine_value)}</Cell><Cell>{item.estimated_life_hours.toLocaleString('pt-BR')} h</Cell><Actions onEdit={() => { setEditing(item); setOpen(true) }} onDelete={() => setDeleting(item)} /></tr>)}</Table>}
    <Modal open={open} onClose={close} title={editing ? 'Editar máquina' : 'Adicionar máquina'} footer={<><Button variant="outline" onClick={close}>Cancelar</Button><Button type="submit" form="machine-form" loading={saving}>Salvar máquina</Button></>}><form id="machine-form" key={editing?.id ?? 'new'} className="grid gap-4 sm:grid-cols-2" onSubmit={submit}><Input containerClassName="sm:col-span-2" name="model" label="Modelo da impressora *" defaultValue={editing?.model} required /><NumberInput name="consumption_watts" label="Consumo em watts *" defaultValue={editing?.consumption_watts} required /><MoneyInput name="maintenance_per_hour" label="Manutenção em R$/h *" defaultValue={editing?.maintenance_per_hour} required /><MoneyInput name="machine_value" label="Valor da máquina *" defaultValue={editing?.machine_value} required /><NumberInput name="estimated_life_hours" label="Vida útil em horas *" defaultValue={editing?.estimated_life_hours ?? 10000} min="1" required /></form></Modal>
    <ConfirmDialog open={Boolean(deleting)} title="Excluir máquina?" description="Confirme a exclusão. Máquinas vinculadas a orçamentos ou projetos não podem ser excluídas." confirmLabel="Excluir" onCancel={() => setDeleting(null)} onConfirm={() => void remove()} />
  </Card>
}

function SuppliesPanel() {
  const hook = useSupplies(); const { showToast } = useToast(); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<SupplyRow | null>(null); const [deleting, setDeleting] = useState<SupplyRow | null>(null); const [saving, setSaving] = useState(false)
  const close = () => { setOpen(false); setEditing(null) }
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const total = parseNumberBR(String(data.get('total_price'))); const quantity = parseNumberBR(String(data.get('quantity_purchased'))); const input: SupplyInput = { name: String(data.get('name')).trim(), total_price: total, quantity_purchased: quantity, unit: String(data.get('unit')) as SupplyUnit, unit_cost: quantity > 0 ? total / quantity : 0, stock_quantity: quantity }; if (!input.name || total < 0 || quantity <= 0) { showToast('Preencha corretamente os campos obrigatórios.', 'error'); return } setSaving(true); try { await hook.saveSupply(input, editing?.id); showToast(editing ? 'Insumo atualizado com sucesso.' : 'Insumo cadastrado com sucesso.', 'success'); close() } catch (error) { showToast(getDatabaseErrorMessage(error, 'Erro ao salvar insumo.'), 'error') } finally { setSaving(false) } }
  const remove = async () => { if (!deleting) return; try { await hook.deleteSupply(deleting.id); showToast('Insumo excluído com sucesso.', 'success'); setDeleting(null) } catch (error) { showToast(getDatabaseErrorMessage(error, 'Erro ao excluir insumo.'), 'error') } }
  return <Card title="Insumos e embalagens" description="Calcule automaticamente o custo unitário de cada item." action={<Button onClick={() => setOpen(true)}><Plus size={18} />Adicionar insumo</Button>}>{hook.loading ? <DataLoading /> : hook.error ? <DataError message={getDatabaseErrorMessage(new Error(hook.error), 'Erro ao carregar insumos.')} /> : hook.supplies.length === 0 ? <EmptyState icon={Box} title="Nenhum insumo cadastrado" description="Cadastre embalagens e materiais auxiliares usados nos projetos." action={<Button onClick={() => setOpen(true)}><Plus size={18} />Adicionar insumo</Button>} /> : <Table headers={['Item', 'Quantidade', 'Unidade', 'Preço total', 'Custo unitário', 'Ações']}>{hook.supplies.map((item) => <tr key={item.id}><Cell strong>{item.name}</Cell><Cell>{item.quantity_purchased.toLocaleString('pt-BR')}</Cell><Cell>{item.unit}</Cell><Cell>{formatCurrency(item.total_price)}</Cell><Cell success>{formatCurrency(item.unit_cost)}</Cell><Actions onEdit={() => { setEditing(item); setOpen(true) }} onDelete={() => setDeleting(item)} /></tr>)}</Table>}
    <Modal open={open} onClose={close} title={editing ? 'Editar insumo' : 'Adicionar insumo'} footer={<><Button variant="outline" onClick={close}>Cancelar</Button><Button type="submit" form="supply-form" loading={saving}>Salvar item</Button></>}><form id="supply-form" key={editing?.id ?? 'new'} className="grid gap-4 sm:grid-cols-2" onSubmit={submit}><Input containerClassName="sm:col-span-2" name="name" label="Nome do item *" defaultValue={editing?.name} required /><MoneyInput name="total_price" label="Preço total pago *" defaultValue={editing?.total_price} required /><NumberInput name="quantity_purchased" label="Quantidade comprada *" defaultValue={editing?.quantity_purchased} min="0.001" required /><Select containerClassName="sm:col-span-2" name="unit" label="Unidade de medida *" defaultValue={editing?.unit ?? 'unidades'}>{['unidades', 'metros', 'gramas', 'kg', 'pacote', 'litros', 'ml'].map((unit) => <option key={unit} value={unit}>{unit}</option>)}</Select></form></Modal>
    <ConfirmDialog open={Boolean(deleting)} title="Excluir insumo?" description="Confirme a exclusão. Insumos vinculados a orçamentos não podem ser excluídos." confirmLabel="Excluir" onCancel={() => setDeleting(null)} onConfirm={() => void remove()} />
  </Card>
}

function SettingsPanel() {
  const hook = useSettings(); const { showToast } = useToast(); const [saving, setSaving] = useState(false)
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const input: SettingsInput = { energy_price_kwh: parseNumberBR(String(data.get('energy_price_kwh'))), failure_margin_percent: parseNumberBR(String(data.get('failure_margin_percent'))), markup_percent: parseNumberBR(String(data.get('markup_percent'))), taxes_percent: parseNumberBR(String(data.get('taxes_percent'))), card_fee_percent: parseNumberBR(String(data.get('card_fee_percent'))), fixed_ads_cost: parseNumberBR(String(data.get('fixed_ads_cost'))) }; if (Object.values(input).some((value) => value < 0)) { showToast('Os parâmetros não podem ser negativos.', 'error'); return } setSaving(true); try { await hook.saveSettings(input); showToast('Parâmetros salvos com sucesso.', 'success') } catch (error) { showToast(getDatabaseErrorMessage(error, 'Erro ao salvar parâmetros.'), 'error') } finally { setSaving(false) } }
  return <Card title="Parâmetros globais" description="Estes valores serão usados automaticamente na calculadora.">{hook.loading ? <DataLoading /> : hook.error ? <DataError message={getDatabaseErrorMessage(new Error(hook.error), 'Erro ao carregar parâmetros.')} /> : hook.settings && <form key={hook.settings.updated_at} className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3" onSubmit={submit}><MoneyInput name="energy_price_kwh" label="Energia em R$/kWh" defaultValue={hook.settings.energy_price_kwh} /><NumberInput name="failure_margin_percent" label="Margem de falha (%)" defaultValue={hook.settings.failure_margin_percent} /><NumberInput name="markup_percent" label="Markup global (%)" defaultValue={hook.settings.markup_percent} /><NumberInput name="taxes_percent" label="Impostos (%)" defaultValue={hook.settings.taxes_percent} /><NumberInput name="card_fee_percent" label="Taxa de cartão (%)" defaultValue={hook.settings.card_fee_percent} /><MoneyInput name="fixed_ads_cost" label="Publicidade fixa" defaultValue={hook.settings.fixed_ads_cost} /><div className="sm:col-span-2 lg:col-span-3"><Button type="submit" loading={saving}>Salvar parâmetros</Button></div></form>}</Card>
}

function Cell({ children, strong, success }: { children: React.ReactNode; strong?: boolean; success?: boolean }) { return <td className={`whitespace-nowrap px-4 py-3 ${strong ? 'font-semibold text-slate-900' : success ? 'font-semibold text-success' : 'text-slate-600'}`}>{children}</td> }
function Actions({ onEdit, onDelete }: { onEdit: () => void; onDelete: () => void }) { return <td className="whitespace-nowrap px-4 py-2"><div className="flex gap-1"><Button variant="ghost" className="min-h-9 px-2" onClick={onEdit} aria-label="Editar"><Pencil size={17} /></Button><Button variant="ghost" className="min-h-9 px-2 text-danger hover:bg-red-50" onClick={onDelete} aria-label="Excluir"><Trash2 size={17} /></Button></div></td> }
function nullable(value: FormDataEntryValue | null): string | null { const text = String(value ?? '').trim(); return text || null }
