import { Minus, PackageCheck, Pencil, Plus, Trash2 } from 'lucide-react'
import { useMemo, useState } from 'react'
import { MoneyInput } from '../../components/forms/MoneyInput'
import { NumberInput } from '../../components/forms/NumberInput'
import { Button } from '../../components/ui/Button'
import { Card } from '../../components/ui/Card'
import { ConfirmDialog } from '../../components/ui/ConfirmDialog'
import { DataError, DataLoading } from '../../components/ui/DataState'
import { EmptyState } from '../../components/ui/EmptyState'
import { Input } from '../../components/ui/Input'
import { Modal } from '../../components/ui/Modal'
import { Select } from '../../components/ui/Select'
import { Textarea } from '../../components/ui/Textarea'
import { useToast } from '../../components/ui/Toast'
import { useProjects } from '../../hooks/useProjects'
import { useReadyStock, type ReadyStockInput } from '../../hooks/useReadyStock'
import { getDatabaseErrorMessage } from '../../lib/databaseErrors'
import { formatCurrency, parseNumberBR } from '../../lib/formatters'
import type { ReadyStockRow } from '../../types/database'

const empty: ReadyStockInput = { projectModelId: null, name: '', quantity: 1, unitCost: 0, salePrice: 0, imageUrl: '', notes: '' }

export function Stock() {
  const hook = useReadyStock(); const projects = useProjects(); const { showToast } = useToast(); const [open, setOpen] = useState(false); const [draft, setDraft] = useState<ReadyStockInput>(empty); const [editing, setEditing] = useState<ReadyStockRow | null>(null); const [deleting, setDeleting] = useState<ReadyStockRow | null>(null); const [selling, setSelling] = useState<ReadyStockRow | null>(null); const [saleQuantity, setSaleQuantity] = useState(1); const [deduct, setDeduct] = useState(false); const [saving, setSaving] = useState(false)
  const totals = useMemo(() => ({ pieces: hook.products.reduce((sum, item) => sum + item.quantity, 0), value: hook.products.reduce((sum, item) => sum + item.quantity * item.unit_cost, 0) }), [hook.products])
  const set = <K extends keyof ReadyStockInput>(key: K, value: ReadyStockInput[K]) => setDraft((current) => ({ ...current, [key]: value }))
  const close = () => { setOpen(false); setEditing(null); setDraft(empty); setDeduct(false) }
  const startEdit = (product: ReadyStockRow) => { setEditing(product); setDraft({ projectModelId: product.project_model_id, name: product.name, quantity: product.quantity, unitCost: product.unit_cost, salePrice: product.sale_price, imageUrl: product.image_url ?? '', notes: product.notes ?? '' }); setOpen(true) }
  const save = async () => { if (!draft.name.trim() || draft.quantity <= 0 || draft.unitCost < 0 || draft.salePrice < 0) { showToast('Preencha nome, quantidade e valores corretamente.', 'error'); return } if (deduct && !draft.projectModelId) { showToast('Selecione um modelo para dar baixa automática.', 'error'); return } setSaving(true); try { await hook.saveProduct(draft, editing?.id, !editing && deduct); showToast(editing ? 'Produto atualizado com sucesso.' : 'Produto adicionado ao estoque.', 'success'); close() } catch (error) { showToast(getDatabaseErrorMessage(error, error instanceof Error ? error.message : 'Erro ao salvar produto.'), 'error') } finally { setSaving(false) } }
  const remove = async () => { if (!deleting) return; try { await hook.deleteProduct(deleting.id); showToast('Produto removido do estoque.', 'success'); setDeleting(null) } catch (error) { showToast(getDatabaseErrorMessage(error, 'Erro ao remover produto.'), 'error') } }
  const sell = async () => { if (!selling) return; try { await hook.sellProduct(selling, saleQuantity); showToast('Quantidade vendida baixada com sucesso.', 'success'); setSelling(null); setSaleQuantity(1) } catch (error) { showToast(getDatabaseErrorMessage(error, error instanceof Error ? error.message : 'Erro ao baixar venda.'), 'error') } }
  const loading = hook.loading || projects.loading; const error = hook.error ?? projects.error
  return <div className="space-y-6"><div className="grid gap-4 sm:grid-cols-2"><Metric label="Total de peças em estoque" value={totals.pieces.toLocaleString('pt-BR')} /><Metric label="Valor parado em estoque" value={formatCurrency(totals.value)} /></div><Card title="Produtos prontos" description="Controle peças disponíveis para pronta entrega." action={<Button onClick={() => { setDraft(empty); setOpen(true) }}><Plus size={18} />Adicionar produto</Button>}>{loading ? <DataLoading /> : error ? <DataError message={getDatabaseErrorMessage(new Error(error), 'Erro ao carregar estoque.')} /> : hook.products.length === 0 ? <EmptyState icon={PackageCheck} title="Estoque de produtos vazio" description="Adicione uma peça pronta e escolha se deseja baixar seus materiais automaticamente." action={<Button onClick={() => setOpen(true)}><Plus size={18} />Adicionar produto</Button>} /> : <div className="grid gap-4 lg:grid-cols-2">{hook.products.map((product) => <article key={product.id} className="rounded-2xl border border-border p-5"><div className="flex gap-4">{product.image_url ? <img src={product.image_url} alt="" className="size-16 rounded-xl object-cover" /> : <span className="grid size-16 shrink-0 place-items-center rounded-xl bg-emerald-50 text-success"><PackageCheck /></span>}<div className="min-w-0 flex-1"><h2 className="truncate font-bold">{product.name}</h2><p className="mt-1 text-sm text-slate-500">{product.quantity} unidade(s)</p><div className="mt-3 flex gap-5 text-sm"><span><small className="block text-slate-500">Custo unitário</small><strong>{formatCurrency(product.unit_cost)}</strong></span><span><small className="block text-slate-500">Preço de venda</small><strong className="text-success">{formatCurrency(product.sale_price)}</strong></span></div></div></div><div className="mt-4 flex flex-wrap gap-2"><Button variant="outline" className="min-h-9 px-3" onClick={() => { setSelling(product); setSaleQuantity(1) }} disabled={product.quantity <= 0}><Minus size={16} />Baixar venda</Button><Button variant="outline" className="min-h-9 px-3" onClick={() => startEdit(product)}><Pencil size={16} />Editar</Button><Button variant="ghost" className="min-h-9 px-3 text-danger hover:bg-red-50" onClick={() => setDeleting(product)}><Trash2 size={16} />Remover</Button></div></article>)}</div>}
      <Modal open={open} onClose={close} title={editing ? 'Editar produto pronto' : 'Adicionar produto pronto'} footer={<><Button variant="outline" onClick={close}>Cancelar</Button><Button loading={saving} onClick={() => void save()}>Salvar produto</Button></>}><div className="grid gap-4 sm:grid-cols-2"><Select containerClassName="sm:col-span-2" label="Projeto / modelo" value={draft.projectModelId ?? ''} onChange={(e) => set('projectModelId', e.target.value || null)}><option value="">Sem modelo vinculado</option>{projects.projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</Select><Input containerClassName="sm:col-span-2" label="Nome do produto *" value={draft.name} onChange={(e) => set('name', e.target.value)} /><NumberInput label="Quantidade *" min="0.001" value={draft.quantity} onChange={(e) => set('quantity', parseNumberBR(e.target.value))} /><MoneyInput label="Custo unitário" value={draft.unitCost} onChange={(e) => set('unitCost', parseNumberBR(e.target.value))} /><MoneyInput label="Preço de venda" value={draft.salePrice} onChange={(e) => set('salePrice', parseNumberBR(e.target.value))} /><Input type="url" label="URL da foto" value={draft.imageUrl} onChange={(e) => set('imageUrl', e.target.value)} /><Textarea containerClassName="sm:col-span-2" label="Observações" value={draft.notes} onChange={(e) => set('notes', e.target.value)} />{!editing && <label className="flex items-start gap-3 rounded-xl border border-blue-200 bg-blue-50 p-4 sm:col-span-2"><input className="mt-1 size-4" type="checkbox" checked={deduct} onChange={(e) => setDeduct(e.target.checked)} /><span><strong className="block text-sm text-slate-900">Dar baixa automática nos materiais</strong><small className="mt-1 block text-slate-600">Usa o filamento e os insumos padrão do modelo selecionado.</small></span></label>}</div></Modal>
      <Modal open={Boolean(selling)} onClose={() => setSelling(null)} title="Baixar quantidade vendida" footer={<><Button variant="outline" onClick={() => setSelling(null)}>Cancelar</Button><Button onClick={() => void sell()}>Confirmar venda</Button></>}><NumberInput label={`Quantidade vendida (disponível: ${selling?.quantity ?? 0})`} min="0.001" max={selling?.quantity} value={saleQuantity} onChange={(e) => setSaleQuantity(parseNumberBR(e.target.value))} /></Modal>
      <ConfirmDialog open={Boolean(deleting)} title="Remover produto?" description="O produto será removido do estoque de peças prontas. Materiais já consumidos não serão devolvidos." confirmLabel="Remover" onCancel={() => setDeleting(null)} onConfirm={() => void remove()} />
    </Card></div>
}

function Metric({ label, value }: { label: string; value: string }) { return <Card><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></Card> }
