import { ArrowRight, Boxes, Calculator, ChartNoAxesCombined, Check, FileText, PackageCheck, ShieldCheck, UsersRound } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Button } from '../../components/ui/Button'

const features = [
  { icon: Calculator, title: 'Cálculo preciso', text: 'Considere material, energia, manutenção, depreciação, falhas e taxas.' },
  { icon: Boxes, title: 'Custos organizados', text: 'Centralize filamentos, máquinas, insumos e parâmetros da sua operação.' },
  { icon: PackageCheck, title: 'Estoque sob controle', text: 'Acompanhe materiais reservados e peças prontas para entrega.' },
  { icon: UsersRound, title: 'Clientes e projetos', text: 'Mantenha seus contatos e modelos recorrentes sempre acessíveis.' },
  { icon: FileText, title: 'Orçamento profissional', text: 'Apresente propostas claras com informações relevantes para o cliente.' },
  { icon: ChartNoAxesCombined, title: 'Visão do resultado', text: 'Entenda o custo, o preço sugerido e o lucro de cada trabalho.' },
]

export function LandingPage() {
  return <>
    <section className="relative overflow-hidden px-4 pb-24 pt-36 sm:px-6 sm:pt-44 lg:px-8"><div className="absolute left-1/2 top-20 size-[580px] -translate-x-1/2 rounded-full bg-primary/20 blur-[130px]" /><div className="absolute -right-24 top-72 size-80 rounded-full bg-accent/10 blur-[100px]" /><div className="relative mx-auto max-w-7xl"><div className="mx-auto max-w-4xl text-center"><span className="inline-flex items-center gap-2 rounded-full border border-blue-400/20 bg-blue-400/10 px-4 py-2 text-sm font-semibold text-blue-300"><ShieldCheck size={17} />Precificação profissional para impressão 3D</span><h1 className="mt-8 text-4xl font-bold leading-tight tracking-tight sm:text-6xl lg:text-7xl">Preço justo para você.<br /><span className="bg-gradient-to-r from-blue-400 to-orange-400 bg-clip-text text-transparent">Orçamento claro para o cliente.</span></h1><p className="mx-auto mt-7 max-w-2xl text-base leading-8 text-slate-400 sm:text-lg">Calcule seus custos reais, organize materiais e transforme cada projeto de impressão 3D em uma decisão comercial segura.</p><div className="mt-10 flex flex-col justify-center gap-3 sm:flex-row"><Link to="/cadastro"><Button className="w-full px-6 sm:w-auto">Começar grátis <ArrowRight size={18} /></Button></Link><Link to="/login"><Button variant="outline" className="w-full border-white/15 bg-white/5 text-white hover:bg-white/10 sm:w-auto">Entrar</Button></Link></div><div className="mt-9 flex flex-col items-center justify-center gap-3 text-sm text-slate-400 sm:flex-row sm:gap-6">{['Custos detalhados', 'Estoque organizado', 'PDF profissional'].map((item) => <span key={item} className="flex items-center gap-2"><Check size={17} className="text-success" />{item}</span>)}</div></div>
    <div className="mx-auto mt-20 max-w-5xl rounded-3xl border border-white/10 bg-white/5 p-3 shadow-2xl shadow-blue-950/30 backdrop-blur"><div className="rounded-2xl bg-slate-50 p-5 text-slate-900 sm:p-8"><div className="flex items-center justify-between border-b border-border pb-5"><div><p className="text-sm text-slate-500">Novo orçamento</p><h2 className="mt-1 text-xl font-bold">Visão dos seus custos</h2></div><span className="rounded-xl bg-blue-50 p-3 text-primary"><Calculator /></span></div><div className="mt-6 grid gap-4 sm:grid-cols-3"><PreviewCard label="Custo de produção" value="R$ 0,00" /><PreviewCard label="Preço sugerido" value="R$ 0,00" highlight /><PreviewCard label="Lucro líquido" value="R$ 0,00" success /></div></div></div></div></section>
    <section className="bg-slate-50 px-4 py-24 text-slate-900 sm:px-6 lg:px-8" id="recursos"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><span className="text-sm font-bold uppercase tracking-wider text-primary">Tudo em um só lugar</span><h2 className="mt-3 text-3xl font-bold sm:text-4xl">Mais clareza para produzir e vender</h2><p className="mt-4 leading-7 text-slate-600">A estrutura que você precisa para sair da estimativa e trabalhar com custos reais.</p></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{features.map(({ icon: Icon, title, text }) => <article key={title} className="rounded-2xl border border-border bg-white p-6 shadow-card"><span className="grid size-12 place-items-center rounded-xl bg-blue-50 text-primary"><Icon size={23} /></span><h3 className="mt-5 text-lg font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></article>)}</div></div></section>
    <section className="px-4 py-24 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="text-center"><span className="text-sm font-bold uppercase tracking-wider text-orange-400">Fluxo simples</span><h2 className="mt-3 text-3xl font-bold sm:text-4xl">Do custo ao orçamento em três passos</h2></div><div className="mt-14 grid gap-8 md:grid-cols-3">{[['01', 'Configure seus custos', 'Cadastre filamentos, impressoras, insumos e parâmetros globais.'], ['02', 'Informe o projeto', 'Preencha tempo, peso, quantidade, cliente e materiais utilizados.'], ['03', 'Apresente o valor', 'Revise o cálculo, salve o orçamento e gere o documento do cliente.']].map(([number, title, text]) => <div key={number} className="text-center"><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-primary text-lg font-bold">{number}</span><h3 className="mt-5 text-lg font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{text}</p></div>)}</div></div></section>
    <section className="border-t border-white/10 px-4 py-20 sm:px-6 lg:px-8"><div className="mx-auto flex max-w-5xl flex-col items-center justify-between gap-8 rounded-3xl bg-gradient-to-r from-primary to-blue-500 p-8 text-center shadow-2xl shadow-blue-950/30 md:flex-row md:p-12 md:text-left"><div><h2 className="text-3xl font-bold">Comece a precificar com confiança.</h2><p className="mt-3 text-blue-100">Organize sua operação e valorize o seu trabalho.</p></div><Link to="/cadastro"><Button variant="secondary" className="px-6">Criar minha conta <ArrowRight size={18} /></Button></Link></div></section>
    <footer className="border-t border-white/10 px-4 py-8 text-center text-sm text-slate-500">© 2026 CalculaPrint 3D. Precificação profissional para impressão 3D.</footer>
  </>
}

function PreviewCard({ label, value, highlight = false, success = false }: { label: string; value: string; highlight?: boolean; success?: boolean }) { return <div className={`rounded-xl border p-4 ${highlight ? 'border-blue-200 bg-blue-50' : 'border-border bg-white'}`}><p className="text-xs font-medium text-slate-500">{label}</p><p className={`mt-2 text-xl font-bold ${success ? 'text-success' : highlight ? 'text-primary' : ''}`}>{value}</p></div> }
